# Site settings
title: Lukas Wilkeer blog
email: lukasc4l@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Sou um amante de desafios, de empreender e aprender.

  Gosto de transmitir conhecimento para todos os que me cercam e acredito que o conhecimento deva ser livre.
  Trabalho com projetos que envolvam tecnologia, principalmente aqueles que mudam a vida das pessoas, para melhor.
  **PS: I love my job**.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cafeepixel.com.br" # the base hostname & protocol for your site
twitter_username: lukaswilkeer
github_username:  lukaswilkeer

# Build settings
markdown: kramdown